// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CPU struct {
	Socket   int    `json:"socket"`
	Physical int    `json:"physical"`
	Logical  int    `json:"logical"`
	Name     string `json:"name"`
	Ghz      string `json:"ghz"`
	Usage    string `json:"usage"`
}

type Net struct {
	Name       string `json:"name"`
	Sent       int    `json:"sent"`
	Recv       int    `json:"recv"`
	PrettySent string `json:"prettySent"`
	PrettyRecv string `json:"prettyRecv"`
}

type RAM struct {
	Total     int `json:"total"`
	Available int `json:"available"`
	Used      int `json:"used"`
	Free      int `json:"free"`
	Active    int `json:"active"`
	Inactive  int `json:"inactive"`
	Wired     int `json:"wired"`
}

type PrettyRAM struct {
	Total     string `json:"total"`
	Available string `json:"available"`
	Used      string `json:"used"`
	Free      string `json:"free"`
	Active    string `json:"active"`
	Inactive  string `json:"inactive"`
	Wired     string `json:"wired"`
}
